package corbaConversion;


/**
* corbaConversion/IConversionRemoteOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Conversion.idl
* jeudi 7 décembre 2023 22 h 07 AST
*/

public interface IConversionRemoteOperations 
{
  double convertirMontant (double mt);
} // interface IConversionRemoteOperations
